Pages/Category.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using WaveShopClient.Pages.Model;

namespace WaveShopClient.Pages;

public class CategoryModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    [BindProperty]
    public Category Generic { get; set; } = new Category();
    [BindProperty]
    public string Type { get; set; } = "Add";

    public CategoryModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public async Task<ActionResult> OnGetAdd()
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            return Page();
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public async Task<ActionResult> OnGetUpdate(string id)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                Type = "Update";
                Generic = await GetCategoryAsync(int.Parse(id));
                return Page();
            }
            catch (Exception ex)
            {
                return RedirectToPage("./Error", string.Empty, new { code = int.Parse(ex.Message) });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public HttpClient? GetPreparedClient(string uri)
    {
        try
        {
            var handler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback =
                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };
            HttpClient client = new HttpClient(handler);
            client.BaseAddress = new Uri(uri);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            return client;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<ActionResult> OnPostAdd(string name, string description)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                Category category = new Category(){
                    Id = -1,
                    Name = name,
                    Description = description,
                    Status = "Activa"
                };
                var client = GetPreparedClient("https://localhost:7278/api/Categories/");
                HttpResponseMessage response = await client.PostAsync(
                    $"",
                    new StringContent(JsonConvert.SerializeObject(category), Encoding.UTF8, "application/json")
                );
                if (response.IsSuccessStatusCode)
                    return RedirectToPage("./Success", string.Empty, new { header = "Categoría agregada exitosamente", urlRedirection = "/Categories", urlTittle = "Ver categorías" });
                throw new Exception();
            }
            catch (Exception)
            {
                return RedirectToPage("./Error", string.Empty, new { code = 500 });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public async Task<ActionResult> OnPostUpdate(string id, string name, string description)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                Category category = await GetCategoryAsync(int.Parse(id));
                category.Name = name;
                category.Description = description;
                var client = GetPreparedClient("https://localhost:7278/api/Categories/");
                HttpResponseMessage response = await client.PutAsync(
                    $"{id}",
                    new StringContent(JsonConvert.SerializeObject(category), Encoding.UTF8, "application/json")
                );
                if (response.IsSuccessStatusCode)
                    return RedirectToPage("./Success", string.Empty, new { header = "Categoría actualizada exitosamente", urlRedirection = "/Categories", urlTittle = "Ver categorías" });
                throw new Exception();
            }
            catch (Exception)
            {
                return RedirectToPage("./Error", string.Empty, new { code = 500 });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    private async Task<Category> GetCategoryAsync(int id)
    {
        var client = GetPreparedClient("https://localhost:7278/api/Categories/detail/");
        HttpResponseMessage response = await client.GetAsync($"{id}");
        if (response.IsSuccessStatusCode)
            return await response.Content.ReadAsAsync<Category>();
        else
            return null;
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WaveShopClient.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    private static string CommonMessage = "Si el problema persiste, favor de contactar a soporte técnico, comunicando el cpdigo y el ID del error.";
    public readonly Dictionary<int, string> Errors = new Dictionary<int, string>()
    {
        {401 , $"Lo sentimos, ocurrió un problema con la autentiación del usuario. {CommonMessage}"},
        {500, $"Lo sentimos, parece que el servidor no esta respondiendo correctamente. {CommonMessage}"},
        {400, $"Lo sentimos, la información ha sido actualizada reciententemente. {CommonMessage}"}
    };

    [BindProperty]
    public int Code { get; set; } = -1;
    [BindProperty]
    public string Message { get; set; } = string.Empty;

    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet(int code)
    {
        Code = code;
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        Message = string.Empty;
    }

    public void OnGetCustomError(int code, string message)
    {
        Code = code;
        Message = message;
    }

}

Pages/Favorites.cshtml.cs
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaveShopClient.Pages.Model;

namespace WaveShopClient.Pages;

public class FavoritesModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    [BindProperty]
    public List<Product> Products { get; set; } = new List<Product>();

    public FavoritesModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public async Task<ActionResult> OnGet()
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                var ID = HttpContext.Session.GetString("id");
                var client = GetPreparedClient("https://localhost:7278/api/Favorites/");
                HttpResponseMessage response = await client.GetAsync($"{ID}");
                if (response.IsSuccessStatusCode)
                {
                    Products = await response.Content.ReadAsAsync<List<Product>>();
                    return Page();
                }
                throw new Exception();
            }
            catch (Exception)
            {
                return RedirectToPage("./Error", string.Empty, new { code = 500 });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public async Task<ActionResult> OnPostRemove(string ID)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                var userId = HttpContext.Session.GetString("id");
                var client = GetPreparedClient("https://localhost:7278/api/Favorites/");
                HttpResponseMessage response = await client.DeleteAsync($"{userId}/{ID}");
                if (response.IsSuccessStatusCode)
                    return RedirectToPage("./Success", string.Empty, new { header = "Producto removido", urlRedirection = "/Favorites", urlTittle = "Ver favoritos" });
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("./Error", string.Empty, new { code = 500 });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public HttpClient? GetPreparedClient(string uri)
    {
        try
        {
            var handler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback =
                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };
            HttpClient client = new HttpClient(handler);
            client.BaseAddress = new Uri(uri);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            return client;
        }
        catch (Exception)
        {
            return null;
        }
    }
}

Pages/Permisses.cshtml.cs
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaveShopClient.Pages.Model;

namespace WaveShopClient.Pages;

public class PermissesModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public PermissesModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Product.cshtml.cs
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using WaveShopClient.Pages.Model;

namespace WaveShopClient.Pages;

public class ProductModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    [BindProperty]
    public Product ProductSelected { get; set; } = new Product();
    [BindProperty]
    public List<Comment> Comments { get; set; } = new List<Comment>();
    [BindProperty]
    public User UserVentor { get; set; }
    [BindProperty]
    public string Quantity { get; set; } = "1";
    [BindProperty]
    public string IsCorrect { get; set; } = "Yes";
    [BindProperty]
    public string ErrorMessage { get; set; } = string.Empty;
    [BindProperty]
    public string CategoryProduct { get; set; } = "Publicación libre";

    public ProductModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public HttpClient? GetPreparedClient(string uri)
    {
        try
        {
            var handler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback =
                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };
            HttpClient client = new HttpClient(handler);
            client.BaseAddress = new Uri(uri);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            return client;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<ActionResult> OnGet(string ID)
    {
        try
        {
            await GetProduct(ID);
            await GetUserVentor(ProductSelected.IdVendor.ToString());
            await GetComments(ID);
            var category = await GetCategory(ProductSelected.IdCategory);
            CategoryProduct = string.IsNullOrEmpty(category) ? "Libre" : category;
            return Page();
        }
        catch (Exception)
        {
            return RedirectToPage("./Error", string.Empty, new { code = 500 });
        }

    }

    private async Task<Product> GetProduct(string productId)
    {
        var client = GetPreparedClient("https://localhost:7278/api/Products/");
        HttpResponseMessage response = await client.GetAsync($"{productId}");
        if (response.IsSuccessStatusCode)
            ProductSelected = await response.Content.ReadAsAsync<Product>();
        return ProductSelected;
    }

    private async Task<string> GetCategory(int? id)
    {
        try
        {
            var client = GetPreparedClient("https://localhost:7278/api/Categories/detail/");
            HttpResponseMessage response = await client.GetAsync($"{id}");
            if (response.IsSuccessStatusCode)
                return CategoryProduct = (await response.Content.ReadAsAsync<Category>()).Name;
            else
                return string.Empty;
        }
        catch (Exception)
        {
            return string.Empty;
        }
    }

    private async Task<List<Comment>> GetComments(string idProduct)
    {
        var client = GetPreparedClient("https://localhost:7278/api/Comments/");
        HttpResponseMessage response = await client.GetAsync($"{idProduct}");
        if (response.IsSuccessStatusCode)
            Comments = await response.Content.ReadAsAsync<List<Comment>>();
        return Comments;
    }

    private async Task<User> GetUserVentor(string userId)
    {
        var client = GetPreparedClient("https://localhost:7278/api/Users/");
        HttpResponseMessage response = await client.GetAsync($"{userId}");
        if (response.IsSuccessStatusCode)
            UserVentor = await response.Content.ReadAsAsync<User>();
        return UserVentor;
    }

    public async Task<ActionResult> OnPostBuyProduct(string idProduct, string productQuantity)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                await GetProduct(idProduct);
                await GetUserVentor(ProductSelected.IdVendor.ToString());
                if (ProductSelected.StockQuantity < Convert.ToInt32(productQuantity))
                    throw new Exception("Lo sentimos, no hay suficiente cantidad en el stock del producto");
                return RedirectToPage("./ShopNote", "UnitProductShow", new { id = idProduct, quantity = productQuantity });
            }
            catch (Exception ex)
            {
                IsCorrect = "No";
                ErrorMessage = ex.Message;
                return Page();
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public async Task<IActionResult> OnPostAddShoppingCart(string idProduct, string productQuantity)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                await GetProduct(idProduct);
                await GetUserVentor(ProductSelected.IdVendor.ToString());
                if (ProductSelected.StockQuantity < Convert.ToInt32(productQuantity))
                    throw new Exception("Lo sentimos, no hay suficiente cantidad en el stock del producto");
                ProductSelected.StockQuantity = Convert.ToInt32(productQuantity);
                var idUser = HttpContext.Session.GetString("id");
                var client = GetPreparedClient("https://localhost:7278/api/ShoppingCart/");
                HttpResponseMessage response = await client.PostAsync
                (
                    $"{idUser}",
                    new StringContent(JsonConvert.SerializeObject(ProductSelected), Encoding.UTF8, "application/json")
                );
                if (response.IsSuccessStatusCode)
                    return RedirectToPage("./Success", string.Empty, new { header = "Producto agregado al carrito", urlRedirection = "/ShoppingCart", urlTittle = "Ver carrito" });
                else
                    throw new Exception("500");
            }
            catch (Exception ex)
            {
                int code;
                if (int.TryParse(ex.Message, out code))
                {
                    return RedirectToPage("./Error", string.Empty, new { code = int.Parse(ex.Message) });
                }
                else
                {
                    IsCorrect = "No";
                    ErrorMessage = ex.Message;
                    return Page();
                }
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }

    public async Task<IActionResult> OnGetAddFav(int idProduct)
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("id")))
        {
            try
            {
                var idUser = HttpContext.Session.GetString("id");
                var client = GetPreparedClient("https://localhost:7278/api/Favorites/");
                HttpResponseMessage response = await client.PostAsync($"{idUser}/{idProduct}", null);
                if (response.IsSuccessStatusCode)
                    return RedirectToPage("./Success", string.Empty, new { header = "Producto agregado a favoritos", urlRedirection = "/Favorites", urlTittle = "Ver favoritos" });
                throw new Exception("500");
            }
            catch (Exception ex)
            {
                return RedirectToPage("./Error", string.Empty, new { code = 500 });
            }
        }
        else
        {
            return RedirectToPage("./SignInRequire");
        }
    }
}

Pages/Categories.cshtml
@page
@model CategoriesModel
@{
    ViewData["Title"] = "Ctegories";
}

<style>
    .card:hover {
        box-shadow: 10px 10px 5px palegoldenrod;
        transition-duration: .3s;
    }

    .card {
        transition-duration: .3s;
        padding: 1em;
        font-size: small;
    }

    img {
        width: 7em;
    }

    a{
        text-decoration: none;
    }


    .cmn-divfloat {
        position: fixed !important;
        bottom: 45px;
        right: 15px;
        z-index: 100;
    }

    .cmn-btncircle {
        width: 250px !important;
        height: 40px !important;
        padding: 6px 0px;
        border-radius: 15px;
        font-size: 18px;
        text-align: calc();
    }
</style>

<div id="div-totop" class="cmn-divfloat">
    <a asp-page="/Category" asp-page-handler="Add" class="btn btn-primary cmn-btncircle">
        Agregar nueva categoría
    </a>
</div>

<div class="container card shadow-lg mt-4">
    @{
        <div class="card-header">
            <h2></h2>
        </div>
        <div class="card-body">
            <table class="table table-hover mt-4">
                <thead>
                    <tr>
                        <th>#Id</th>
                        <th>Nombre del categoría</th>
                        <th>Descripción</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in @Model.Categories)
                    {
                        <tr>
                            <td><a asp-page="/Category" asp-page-handler="Update" asp-route-id="@category.Id"> @category.Id </a></td>
                            <td>@category.Name</td>
                            <td>@category.Description</td>
                            <td>@category.Status</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    }
</div>


@section Scripts {
<script>
    $(document).ready(() => {

    });
</script>
}

Pages/Category.cshtml
@page
@model CategoryModel
@{
    ViewData["Title"] = "Category data";
}

<style>
    .card:hover {
        box-shadow: 10px 10px 5px palegoldenrod;
        transition-duration: .3s;
    }

    .card {
        transition-duration: .3s;
        padding: 1em;
    }

    img {
        width: 7em;
    }

    a {
        text-decoration: none;
    }
</style>

<div class="container col-md-8 col-sm-8 col-lg-4 mt-4">
    @{
        <div class="card shadow-lg">
            <div class="card-header">
                <h2>Categoría</h2>
            </div>
            <div class="card-body">
                <form id="formdata" method="post">
                    <div class="row">
                        <label for="name" class="form-label">Nombre de la categoría</label>
                        <input name="name" type="text" value="@Model.Generic.Name" class="form-control" id="name">
                    </div>
                    <div class="row mb-5">
                        <label for="description" class="form-label">Descripción</label>
                        <textarea name="description" type="text" class="form-control" id="description">@Model.Generic.Description</textarea>
                    </div>
                    @if (Model.Type == "Update")
                    {
                        <button asp-page-handler="Update" asp-route-id="@Model.Generic.Id" style="width: 100%;"
                    class="btn btn-outline-primary">Actualizar</button>
                    }
                    else
                    {
                        <button asp-page-handler="Add" style="width: 100%;" 
                    class="btn btn-outline-primary">Agregar</button>
                    }
                </form>
            </div>
            <div class="card-footer pt-4">
                <small>Estos campos fungirán como valores de búsqueda de los productos</small>
            </div>
        </div>
    }
</div>


@section Scripts {
<script>
    $(document).ready(() => {

    });
</script>
}

Pages/Product.cshtml
@page
@model ProductModel
@{
    ViewData["Title"] = "Product page";
}

<style>
    a{
        text-decoration: none;
        color: black;
    }

    a:hover{
        color: blue;
    }

    .horizontal-scrollable > .row {
        overflow-x: auto;
        white-space: nowrap;
    }
        
    .horizontal-scrollable > .row > .col-xs-4 {
        display: inline-block;
        float: none;
    }

    .container-img {
        position: relative;
        display: inline-block;
        width: 7em;
        height: 5em;
    }

    .image {
        opacity: 1;
        display: block;
        width: 100%;
        height: 100%;
        transition: .5s ease;
        backface-visibility: hidden;
    }

    .middle {
        transition: .5s ease;
        opacity: 0;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        text-align: center;
    }

    .container-img:hover .image {
        opacity: 0.3;
    }

    .container-img:hover .middle {
        opacity: 1;
    }

    .text-img {
        background-color: transparent;
        color: black;
        font-size: 16px;
        padding: 16px 32px;
    }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <div class="card shadow-lg p-3 m-4 rounded">
                <div class="card-header">
                    <span class="badge rounded-pill bg-primary m-2">@Model.CategoryProduct</span>
                    <h4 class="card-title mb-3">@Model.ProductSelected.Name</h4>
                    @if (Model.IsCorrect != "Yes")
                    {
                        <div class="alert alert-danger mt-4" role="alert">
                            @Model.ErrorMessage
                        </div>
                    }
                    <img id="mainImage" class="img-fluid rounded" src="@Model.ProductSelected.Product_Images.ToArray()[0].Url" alt="">
                    <div class="container-fluid horizontal-scrollable p-0">
                        @foreach (var im in @Model.ProductSelected.Product_Images)
                        {
                            <div class="container-img m-2">
                                <img src="@im.Url" alt="Avatar" class="image rounded p-1 shadow" style="width:100%">
                            </div>
                        }
                    </div>
                </div>
                <div class="card-body">
                    <form id="formdata" name="formdata" method="post">
                        <div class="container-fluid d-flex p-0 mb-3">
                            <a href="">
                                <span class="material-icons me-1">
                                    thumb_down_alt
                                </span>
                            </a>
                            <small class="text-muted me-4">@Model.ProductSelected.LikesNumber likes</small>
                            <a href="">
                                <span class="material-icons me-1">
                                    thumb_up_alt
                                </span>
                            </a>
                            <small class="text-muted me-4">@Model.ProductSelected.DislikesNumber dislikes</small>
                            <a asp-page="/Product" asp-page-handler="AddFav" asp-route-idProduct="@Model.ProductSelected.Id">
                                <span class="material-icons me-3">
                                    favorite
                                </span>
                            </a>
                            <small class="text-muted">@Model.ProductSelected.ShoppedTimes unidades
                                vendidas
                            </small>
                        </div>
                        <label for="" class="fs-1">$ @Model.ProductSelected.UnitPrice</label>
                        <div class="input-group mt-4 mb-3">
                            <span class="input-group-text" id="basic-addon1">Cantidad</span>
                            <input id="productQuantity" name="productQuantity" type="number" class="form-control" value="@Model.Quantity"
                                aria-label="Username" aria-describedby="basic-addon1">
                            <input name="idProduct" value="@Model.ProductSelected.Id" hidden>
                        </div>
                        <div class="row">
                            <div class="col-md-6 d-grid">
                                <button type="submit" asp-page-handler="BuyProduct"
                                    class="btn btn-primary btn-block mt-2 mb-2">Comprar</button>
                            </div>
                            <div class="col-md-6 d-grid">
                                <button type="submit" asp-page-handler="AddShoppingCart"
                                    class="btn btn-outline-primary d-block mt-2 mb-2">Agregar al
                                    carrito</button>
                            </div>
                        </div>
                    </form>
                    <h5 class="text mt-3">Características</h5>
                    <table class="table table-striped table-hover mt-3">
                        <tbody>
                            <tr>
                                <th scope="row" class="col-4">Unidades disponibles</th>
                                <td>@Model.ProductSelected.StockQuantity</td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-4">Precio por unidad</th>
                                <td>$@Model.ProductSelected.UnitPrice</td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-4">Fecha de actualización</th>
                                <td>@Model.ProductSelected.UnitPrice</td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-4">País</th>
                                <td>@Model.ProductSelected.Country</td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-4">Ubicación</th>
                                <td>@Model.ProductSelected.Location</td>
                            </tr>
                        </tbody>
                    </table>
                    <h5 class="text mt-5">Descripción</h5>
                    <hr class="my-4">
                    <p style="text-align: justify;">
                        @Model.ProductSelected.Description
                    </p>
                    <h5 class="text mt-5">Infromación del vendedor</h5>
                    <hr class="my-4">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th scope="row" class="col-6">Nombre de usuario</th>
                                <td><a asp-page="/UserData" asp-route-id="@Model.UserVentor.Id"> @Model.UserVentor.UserName </a></td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-6">Reputación</th>
                                <td>@Model.UserVentor.Reputation</td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-6">Teléfono</th>
                                <td>@Model.UserVentor.Phone</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Última actualización @Model.ProductSelected.LastUpdate</small>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card shadow p-3 m-4 rounded">
                <div class="container-fuild m-3">
                    <label class="text mb-1" for="staticEmail2">Escribe un comentario</label>
                    <form class="row">
                        <div class="col-8">
                            <textarea type="text" class="form-control" id="inputPassword2"
                                placeholder="Comentario"></textarea>
                        </div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary">Publicar</button>
                        </div>
                    </form>
                </div>
                <hr class="my-4">
                @{
                    if(@Model.Comments.Count > 0){
                        foreach (var comment in @Model.Comments)
                        {
                            <div class="card m-3">
                                <div class="card-body">
                                    <h5 class="card-title">@comment.OpinionResume</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">Por: @comment.UserName</h6>
                                    <p class="card-text">@comment.Content</p>
                                    <a href="#" class="card-link">@comment.Likes Likes</a>
                                    <a href="#" class="card-link">@comment.Dislikes Dislikes</a>
                                </div>
                            </div>
                        } 
                    }else{
                        <div class="conatiner" style="text-align: center; color: #747474;">
                            <label class="text"><b>Se el primero en comentar</b></label>
                        </div>    
                    }
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script>
    $(document).ready(() => {

        $('.image').click(function () {
            var newSrc = $(this).attr('src');
            $('#mainImage').attr('src', newSrc);
        });
    
    });
</script>
}